# Generated by Django 4.1.6 on 2023-02-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=200, verbose_name='Статус')),
                ('complete_data', models.DateField(blank=True, default='', verbose_name='Дата выполнения')),
            ],
        ),
    ]
