# Generated by Django 4.1.6 on 2023-02-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
