# Generated by Django 4.1.6 on 2023-02-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_task_complete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Подробное описание'),
        ),
    ]
